executors:
  node:
    parameters:
      image:
        type: string
        default: "10"
    docker:
      - image: circleci/node:<< parameters.image >>

aliases:
  restore_cache: &restore_cache
    restore_cache:
      name: Restore node_modules cache
      keys:
        - yarn-cache-{{ checksum "yarn.lock" }}

  install_node_modules: &install_node_modules
    run:
      name: Install node modules
      command: yarn --frozen-lockfile

  persist_cache: &persist_cache
    save_cache:
      name: Save node modules cache
      key: yarn-cache-{{ checksum "yarn.lock" }}
      paths:
        - ~/.cache

commands:
  tf:
    parameters:
      command:
        type: string
        default: "plan"
    steps:
      - checkout
      - run: echo 'export PATH=/tmp/tf:$PATH' >> $BASH_ENV
      - run:
          name: Install Terraform
          command: |
            mkdir -p /tmp/tf/
            wget https://releases.hashicorp.com/terraform/0.11.13/terraform_0.11.13_linux_amd64.zip
            unzip terraform_0.11.13_linux_amd64.zip -d /tmp/tf
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *persist_cache
      - run:
          name: Terraform Plan
          command: |
            terraform << parameters.command >> -out tfplan.tf \
              -var='client_email=${CLIENT_EMAIL}'
              -var='private_key=${PRIVATE_KEY}'
          working_directory: ~/project/terraform

version: 2.1
jobs:
  build:
    executor: node
    steps:
      - checkout
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *persist_cache
      - run: yarn build
  plan:
    executor: node
    steps:
      - tf:
          command: plan

  apply:
    executor: node
    steps:
      - tf:
          command: apply

workflows:
  version: 2
  deploy:
    jobs:
      - build
      - plan
